### ISSUE TITLE
dragula

### ISSUE THREAD

**Issue by taozhiw** [taozhiw/blog#8]
## dragula 拖动 table 的 tr 无法设置宽度问题。

因为 tr  在拖动前的样式为：
```css
display: table-row;
```
导致在拖动过程中对其设置宽度无效，实验发现当 tr 的显示属性设置为如下时，可设置宽度：
```css
display: inline-table;
```
所以只需要在 dragula 拖动的钩子样式上添加下面的样式即可：
```css
tr.gu-mirror {
  display: inline-table;
}
```
